version: '3.9'

services:
  db:
    image: postgres:15
    container_name: system_monitoring_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: system_monitoring
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: system_monitoring_app
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8001:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/system_monitoring
    volumes:
      - .:/app

volumes:
  postgres_data:
