"""model creation for metrics alerts and users

Revision ID: 8f029a8b89c6
Revises: 0afc7a5354ae
Create Date: 2025-08-21 04:39:21.276503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8f029a8b89c6'
down_revision: Union[str, Sequence[str], None] = '0afc7a5354ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metrics', sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_column('metrics', 'time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metrics', sa.Column('time', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('metrics', 'ts')
    # ### end Alembic commands ###
